var hierarchy =
[
    [ "_2devent", "d7/dff/struct__2devent.html", null ],
    [ "_evt_raw", "db/d82/struct__evt__raw.html", null ],
    [ "_RGBColor", "d0/d8a/struct___r_g_b_color.html", null ],
    [ "AcromageCardOnTable", "dc/dd2/struct_acromage_card_on_table.html", null ],
    [ "ActionQueue", "da/d47/struct_action_queue.html", null ],
    [ "Actor", "da/d35/struct_actor.html", null ],
    [ "ActorJob", "d8/d31/struct_actor_job.html", null ],
    [ "AIDirection", "df/da0/struct_a_i_direction.html", null ],
    [ "am_ai_cardpowerstruct", "dc/d88/structam__ai__cardpowerstruct.html", null ],
    [ "am_effects_struct", "d1/d37/structam__effects__struct.html", null ],
    [ "Application", "de/d6b/class_application.html", null ],
    [ "ApplicationConfig", "d5/d47/struct_application_config.html", null ],
    [ "arcomage_mouse", "de/d75/structarcomage__mouse.html", null ],
    [ "ArcomageCard", "db/def/struct_arcomage_card.html", null ],
    [ "ArcomageDeck", "d7/dd9/struct_arcomage_deck.html", null ],
    [ "ArcomageGame", "d1/d67/struct_arcomage_game.html", null ],
    [ "ArcomageGame_InputMSG", "d1/d84/struct_arcomage_game___input_m_s_g.html", null ],
    [ "ArcomagePlayer", "d7/da6/struct_arcomage_player.html", null ],
    [ "ArcomageStartConditions", "d2/dd8/struct_arcomage_start_conditions.html", null ],
    [ "array", null, [
      [ "NZIArray< _Ty, _Size >", "d9/d69/class_n_z_i_array.html", null ],
      [ "NZIArray< ItemDesc, 800 >", "d9/d69/class_n_z_i_array.html", null ]
    ] ],
    [ "AssetsManager", "db/dd6/class_assets_manager.html", null ],
    [ "AudioPlayer", "d7/dc2/class_audio_player.html", null ],
    [ "Autonote", "d5/dde/struct_autonote.html", null ],
    [ "av_alias", "d5/df1/unionav__alias.html", null ],
    [ "av_intfloat32", "d9/d3e/unionav__intfloat32.html", null ],
    [ "av_intfloat64", "de/da5/unionav__intfloat64.html", null ],
    [ "AVABufferSinkParams", "d2/dce/struct_a_v_a_buffer_sink_params.html", null ],
    [ "AVBitStreamFilter", "d1/d8d/struct_a_v_bit_stream_filter.html", null ],
    [ "AVBitStreamFilterContext", "d6/dbd/struct_a_v_bit_stream_filter_context.html", null ],
    [ "AVBlowfish", "d2/db8/struct_a_v_blowfish.html", null ],
    [ "AVBSFContext", "de/d38/struct_a_v_b_s_f_context.html", null ],
    [ "AVBufferRef", "d0/dc0/struct_a_v_buffer_ref.html", null ],
    [ "AVBufferSinkParams", "d4/d85/struct_a_v_buffer_sink_params.html", null ],
    [ "AVBufferSrcParameters", "d4/d9d/struct_a_v_buffer_src_parameters.html", null ],
    [ "AVChapter", "d0/d87/struct_a_v_chapter.html", null ],
    [ "AVClass", "d2/de1/struct_a_v_class.html", null ],
    [ "AVCodec", "df/d2a/struct_a_v_codec.html", null ],
    [ "AVCodecContext", "de/d1f/struct_a_v_codec_context.html", null ],
    [ "AVCodecDescriptor", "db/dcc/struct_a_v_codec_descriptor.html", null ],
    [ "AVCodecHWConfig", "da/d3c/struct_a_v_codec_h_w_config.html", null ],
    [ "AVCodecParameters", "dc/d7f/struct_a_v_codec_parameters.html", null ],
    [ "AVCodecParser", "d6/d65/struct_a_v_codec_parser.html", null ],
    [ "AVCodecParserContext", "d7/da5/struct_a_v_codec_parser_context.html", null ],
    [ "AVComplexFloat", "d8/d8f/struct_a_v_complex_float.html", null ],
    [ "AVComponentDescriptor", "d2/d11/struct_a_v_component_descriptor.html", null ],
    [ "AVContentLightMetadata", "d2/d03/struct_a_v_content_light_metadata.html", null ],
    [ "AVCPBProperties", "df/db2/struct_a_v_c_p_b_properties.html", null ],
    [ "AVCUDADeviceContext", "d4/dba/struct_a_v_c_u_d_a_device_context.html", null ],
    [ "AVD3D11FrameDescriptor", "da/d52/struct_a_v_d3_d11_frame_descriptor.html", null ],
    [ "AVD3D11VAContext", "d0/df5/struct_a_v_d3_d11_v_a_context.html", null ],
    [ "AVD3D11VADeviceContext", "d0/dce/struct_a_v_d3_d11_v_a_device_context.html", null ],
    [ "AVD3D11VAFramesContext", "d0/d8b/struct_a_v_d3_d11_v_a_frames_context.html", null ],
    [ "AVDCT", "d3/d68/struct_a_v_d_c_t.html", null ],
    [ "AVDES", "d3/d7c/struct_a_v_d_e_s.html", null ],
    [ "AVDeviceCapabilitiesQuery", "da/dbf/struct_a_v_device_capabilities_query.html", null ],
    [ "AVDeviceInfo", "de/de5/struct_a_v_device_info.html", null ],
    [ "AVDeviceInfoList", "d4/dc1/struct_a_v_device_info_list.html", null ],
    [ "AVDeviceRect", "d5/d39/struct_a_v_device_rect.html", null ],
    [ "AVDictionaryEntry", "de/d2f/struct_a_v_dictionary_entry.html", null ],
    [ "AVDiracSeqHeader", "d0/d33/struct_a_v_dirac_seq_header.html", null ],
    [ "AVDownmixInfo", "db/dc3/struct_a_v_downmix_info.html", null ],
    [ "AVDRMDeviceContext", "da/d27/struct_a_v_d_r_m_device_context.html", null ],
    [ "AVDRMFrameDescriptor", "de/de3/struct_a_v_d_r_m_frame_descriptor.html", null ],
    [ "AVDRMLayerDescriptor", "d8/d09/struct_a_v_d_r_m_layer_descriptor.html", null ],
    [ "AVDRMObjectDescriptor", "df/dcd/struct_a_v_d_r_m_object_descriptor.html", null ],
    [ "AVDRMPlaneDescriptor", "d9/de3/struct_a_v_d_r_m_plane_descriptor.html", null ],
    [ "AVDVProfile", "d2/de3/struct_a_v_d_v_profile.html", null ],
    [ "AVDXVA2DeviceContext", "dc/d8e/struct_a_v_d_x_v_a2_device_context.html", null ],
    [ "AVDXVA2FramesContext", "dd/dd7/struct_a_v_d_x_v_a2_frames_context.html", null ],
    [ "AVDynamicHDRPlus", "d1/d1d/struct_a_v_dynamic_h_d_r_plus.html", null ],
    [ "AVEncryptionInfo", "d9/dfc/struct_a_v_encryption_info.html", null ],
    [ "AVEncryptionInitInfo", "d4/d3f/struct_a_v_encryption_init_info.html", null ],
    [ "AVFifoBuffer", "d6/dd7/struct_a_v_fifo_buffer.html", null ],
    [ "AVFilter", "de/db5/struct_a_v_filter.html", null ],
    [ "AVFilterContext", "db/d74/struct_a_v_filter_context.html", null ],
    [ "AVFilterGraph", "d4/d5e/struct_a_v_filter_graph.html", null ],
    [ "AVFilterInOut", "d6/d4a/struct_a_v_filter_in_out.html", null ],
    [ "AVFilterLink", "d6/d1a/struct_a_v_filter_link.html", null ],
    [ "AVFormatContext", "de/d85/struct_a_v_format_context.html", null ],
    [ "AVFrame", "d6/d03/struct_a_v_frame.html", null ],
    [ "AVFrameSideData", "d5/d95/struct_a_v_frame_side_data.html", null ],
    [ "AVHDRPlusColorTransformParams", "d7/d46/struct_a_v_h_d_r_plus_color_transform_params.html", null ],
    [ "AVHDRPlusPercentile", "d9/d11/struct_a_v_h_d_r_plus_percentile.html", null ],
    [ "AVHWAccel", "d2/d58/struct_a_v_h_w_accel.html", null ],
    [ "AVHWDeviceContext", "d1/d5e/struct_a_v_h_w_device_context.html", null ],
    [ "AVHWFramesConstraints", "d0/d35/struct_a_v_h_w_frames_constraints.html", null ],
    [ "AVHWFramesContext", "da/d7a/struct_a_v_h_w_frames_context.html", null ],
    [ "AVIndexEntry", "d2/dc6/struct_a_v_index_entry.html", null ],
    [ "AVInputFormat", "d8/dcc/struct_a_v_input_format.html", null ],
    [ "AVIOContext", "d7/dcc/struct_a_v_i_o_context.html", null ],
    [ "AVIODirContext", "dd/d67/struct_a_v_i_o_dir_context.html", null ],
    [ "AVIODirEntry", "d9/d52/struct_a_v_i_o_dir_entry.html", null ],
    [ "AVIOInterruptCB", "da/dc9/struct_a_v_i_o_interrupt_c_b.html", null ],
    [ "AVLFG", "de/d54/struct_a_v_l_f_g.html", null ],
    [ "AVMasteringDisplayMetadata", "dd/d1c/struct_a_v_mastering_display_metadata.html", null ],
    [ "AVMediaCodecContext", "df/d5e/struct_a_v_media_codec_context.html", null ],
    [ "AVMediaCodecDeviceContext", "d0/ded/struct_a_v_media_codec_device_context.html", null ],
    [ "AVMotionVector", "d5/daf/struct_a_v_motion_vector.html", null ],
    [ "AVOption", "d3/ded/struct_a_v_option.html", null ],
    [ "AVOptionRange", "d7/d51/struct_a_v_option_range.html", null ],
    [ "AVOptionRanges", "d4/d7e/struct_a_v_option_ranges.html", null ],
    [ "AVOutputFormat", "d9/d35/struct_a_v_output_format.html", null ],
    [ "AVPacket", "d4/d31/struct_a_v_packet.html", null ],
    [ "AVPacketList", "de/d7b/struct_a_v_packet_list.html", null ],
    [ "AVPacketSideData", "db/d23/struct_a_v_packet_side_data.html", null ],
    [ "AVPanScan", "d6/d2c/struct_a_v_pan_scan.html", null ],
    [ "AVPicture", "d2/ddf/struct_a_v_picture.html", null ],
    [ "AVPixFmtDescriptor", "df/d59/struct_a_v_pix_fmt_descriptor.html", null ],
    [ "AVProbeData", "da/d91/struct_a_v_probe_data.html", null ],
    [ "AVProfile", "d7/dc6/struct_a_v_profile.html", null ],
    [ "AVProgram", "d0/d56/struct_a_v_program.html", null ],
    [ "AVQSVContext", "d3/d6c/struct_a_v_q_s_v_context.html", null ],
    [ "AVQSVDeviceContext", "de/d20/struct_a_v_q_s_v_device_context.html", null ],
    [ "AVQSVFramesContext", "d9/de2/struct_a_v_q_s_v_frames_context.html", null ],
    [ "AVRational", "d7/d28/struct_a_v_rational.html", null ],
    [ "AVRC4", "d5/de5/struct_a_v_r_c4.html", null ],
    [ "AVRegionOfInterest", "d2/d38/struct_a_v_region_of_interest.html", null ],
    [ "AVReplayGain", "d3/d29/struct_a_v_replay_gain.html", null ],
    [ "AVSphericalMapping", "d6/d11/struct_a_v_spherical_mapping.html", null ],
    [ "AVStereo3D", "d0/d37/struct_a_v_stereo3_d.html", null ],
    [ "AVStream", "d4/d6c/struct_a_v_stream.html", null ],
    [ "AVStreamWrapper", "da/ddd/class_a_v_stream_wrapper.html", [
      [ "AVAudioStream", "dc/d4c/class_a_v_audio_stream.html", null ],
      [ "AVVideoStream", "d5/d90/class_a_v_video_stream.html", null ]
    ] ],
    [ "AVSubsampleEncryptionInfo", "d6/d10/struct_a_v_subsample_encryption_info.html", null ],
    [ "AVSubtitle", "d8/d8b/struct_a_v_subtitle.html", null ],
    [ "AVSubtitleRect", "db/d3d/struct_a_v_subtitle_rect.html", null ],
    [ "AVTimecode", "d5/df5/struct_a_v_timecode.html", null ],
    [ "AVVAAPIDeviceContext", "d8/d5f/struct_a_v_v_a_a_p_i_device_context.html", null ],
    [ "AVVAAPIFramesContext", "da/d0c/struct_a_v_v_a_a_p_i_frames_context.html", null ],
    [ "AVVAAPIHWConfig", "dc/df3/struct_a_v_v_a_a_p_i_h_w_config.html", null ],
    [ "AVVDPAUContext", "d0/da5/struct_a_v_v_d_p_a_u_context.html", null ],
    [ "AVVDPAUDeviceContext", "d3/dba/struct_a_v_v_d_p_a_u_device_context.html", null ],
    [ "AVVideotoolboxContext", "d0/d67/struct_a_v_videotoolbox_context.html", null ],
    [ "AVXTEA", "d8/d9a/struct_a_v_x_t_e_a.html", null ],
    [ "Award", "d0/d1a/struct_award.html", null ],
    [ "BBox_int_", "d9/d5c/struct_b_box__int__.html", null ],
    [ "BBox_short_", "df/d81/struct_b_box__short__.html", null ],
    [ "binary_function", null, [
      [ "ci_less", "da/d16/structci__less.html", null ],
      [ "ci_less::nocase_compare", "df/d18/structci__less_1_1nocase__compare.html", null ]
    ] ],
    [ "Bloodsplat", "db/d5a/struct_bloodsplat.html", null ],
    [ "BloodsplatContainer", "da/df2/struct_bloodsplat_container.html", null ],
    [ "BLVDoor", "d1/dcf/struct_b_l_v_door.html", null ],
    [ "BLVFace", "d9/ded/struct_b_l_v_face.html", null ],
    [ "BLVFace_MM7", "d9/d6f/struct_b_l_v_face___m_m7.html", null ],
    [ "BLVFaceExtra", "d2/d5f/struct_b_l_v_face_extra.html", null ],
    [ "BLVHeader", "d8/d34/struct_b_l_v_header.html", null ],
    [ "BLVLightMM6", "d8/df8/struct_b_l_v_light_m_m6.html", null ],
    [ "BLVLightMM7", "d1/dbb/struct_b_l_v_light_m_m7.html", null ],
    [ "BLVLightMM8", "d4/da9/struct_b_l_v_light_m_m8.html", null ],
    [ "BLVMapOutline", "db/d47/struct_b_l_v_map_outline.html", null ],
    [ "BLVMapOutlines", "d1/dd1/struct_b_l_v_map_outlines.html", null ],
    [ "BLVRenderParams", "d4/d1d/struct_b_l_v_render_params.html", null ],
    [ "BLVSector", "d7/d78/struct_b_l_v_sector.html", null ],
    [ "BLVSectorMM8", "de/dc7/struct_b_l_v_sector_m_m8.html", null ],
    [ "BonusRange", "d6/dd6/struct_bonus_range.html", null ],
    [ "BspFace", "d2/db2/struct_bsp_face.html", null ],
    [ "BSPModel", "db/dd9/class_b_s_p_model.html", null ],
    [ "BSPModelData", "d1/d57/struct_b_s_p_model_data.html", null ],
    [ "BSPNode", "db/dfc/struct_b_s_p_node.html", null ],
    [ "BspRenderer", "da/deb/struct_bsp_renderer.html", null ],
    [ "BspRenderer_PortalViewportData", "df/d62/struct_bsp_renderer___portal_viewport_data.html", null ],
    [ "BspRenderer_stru0", "d5/de2/struct_bsp_renderer__stru0.html", null ],
    [ "BSPVertexBuffer", "dc/d29/struct_b_s_p_vertex_buffer.html", null ],
    [ "ByteArray", "dc/db5/struct_byte_array.html", null ],
    [ "CallBackTimer", "d3/d9c/class_call_back_timer.html", null ],
    [ "CastSpellInfo", "db/d9d/struct_cast_spell_info.html", null ],
    [ "CEnchantment", "dd/daf/struct_c_enchantment.html", null ],
    [ "Chest", "db/d0a/struct_chest.html", null ],
    [ "ChestDesc", "db/dc5/struct_chest_desc.html", null ],
    [ "ChestDesc_mm7", "d1/d96/struct_chest_desc__mm7.html", null ],
    [ "ChestList", "d1/d7a/class_chest_list.html", null ],
    [ "CKeyListElement", "d4/dfd/class_c_key_list_element.html", null ],
    [ "ColorFormat", "d9/d78/struct_color_format.html", null ],
    [ "CompressedHeader", "d0/deb/struct_compressed_header.html", null ],
    [ "ConditionProcessor", "d8/dd8/class_condition_processor.html", null ],
    [ "Application::Configuration", "db/dc3/class_application_1_1_configuration.html", null ],
    [ "DDM_DLV_Header", "db/df7/struct_d_d_m___d_l_v___header.html", null ],
    [ "Decal", "d9/d43/struct_decal.html", null ],
    [ "DecalBuilder", "d9/d57/struct_decal_builder.html", null ],
    [ "DecalBuilder_stru0", "d6/d48/struct_decal_builder__stru0.html", null ],
    [ "DecorationDesc_mm6", "df/d16/struct_decoration_desc__mm6.html", [
      [ "DecorationDesc", "dd/dac/struct_decoration_desc.html", null ]
    ] ],
    [ "DecorationList", "dc/d80/class_decoration_list.html", null ],
    [ "DiracVersionInfo", "d9/dbb/struct_dirac_version_info.html", null ],
    [ "LOD::Directory", "d1/db2/struct_l_o_d_1_1_directory.html", null ],
    [ "DMap", "d2/dc1/struct_d_map.html", null ],
    [ "dxva_context", "d0/dad/structdxva__context.html", null ],
    [ "effect_params_struct", "d6/d6c/structeffect__params__struct.html", null ],
    [ "EFXEAXREVERBPROPERTIES", "d0/d71/struct_e_f_x_e_a_x_r_e_v_e_r_b_p_r_o_p_e_r_t_i_e_s.html", null ],
    [ "EGLClientPixmapHI", "d5/de9/struct_e_g_l_client_pixmap_h_i.html", null ],
    [ "Engine", "d6/d83/struct_engine.html", null ],
    [ "Engine_::EngineConfig", "d5/ddb/class_engine___1_1_engine_config.html", null ],
    [ "Engine_::EngineConfigFactory", "d8/d01/class_engine___1_1_engine_config_factory.html", null ],
    [ "Engine_::EngineFactory", "d5/d30/class_engine___1_1_engine_factory.html", null ],
    [ "EquipemntPair", "df/d09/class_equipemnt_pair.html", null ],
    [ "EventIndex", "d7/d21/struct_event_index.html", null ],
    [ "explosion_effect_struct", "db/d55/structexplosion__effect__struct.html", null ],
    [ "FactionTable", "d2/dbc/struct_faction_table.html", null ],
    [ "FFTComplex", "d1/dc8/struct_f_f_t_complex.html", null ],
    [ "LOD::File", "dd/da7/class_l_o_d_1_1_file.html", [
      [ "LOD::WriteableFile", "d6/d34/class_l_o_d_1_1_writeable_file.html", null ],
      [ "LODFile_IconsBitmaps", "d8/d81/class_l_o_d_file___icons_bitmaps.html", null ],
      [ "LODFile_Sprites", "d4/d10/class_l_o_d_file___sprites.html", null ]
    ] ],
    [ "LOD::FileHeader", "dc/d2a/struct_l_o_d_1_1_file_header.html", null ],
    [ "fixed", "d6/dc9/structfixed.html", null ],
    [ "FogProbabilityTableEntry", "d4/d8d/struct_fog_probability_table_entry.html", null ],
    [ "FontData", "d6/d00/struct_font_data.html", null ],
    [ "Format", "d3/dbf/struct_format.html", null ],
    [ "FrameTableTxtLine", "de/dfd/struct_frame_table_txt_line.html", null ],
    [ "Application::Game", "d4/d06/class_application_1_1_game.html", null ],
    [ "Game__StationaryLight", "d0/d35/struct_game_____stationary_light.html", null ],
    [ "Game_Bloodsplat", "d0/d76/struct_game___bloodsplat.html", null ],
    [ "Game_stru0", "d5/d65/struct_game__stru0.html", null ],
    [ "Application::GameFactory", "d4/d6b/class_application_1_1_game_factory.html", null ],
    [ "GameTime", "df/dc2/struct_game_time.html", null ],
    [ "Application::GameWindowHandler", "dc/d12/class_application_1_1_game_window_handler.html", null ],
    [ "GenderTableEntry", "d0/df0/struct_gender_table_entry.html", null ],
    [ "GUIButton", "db/d66/class_g_u_i_button.html", null ],
    [ "GUICharMetric", "d5/d79/struct_g_u_i_char_metric.html", null ],
    [ "GUIFont", "d3/d39/class_g_u_i_font.html", null ],
    [ "GUIMessage", "d3/d8e/struct_g_u_i_message.html", null ],
    [ "GUIMessageQueue", "db/dc9/struct_g_u_i_message_queue.html", null ],
    [ "GUIProgressBar", "dd/dc4/class_g_u_i_progress_bar.html", null ],
    [ "GUIWindow", "d4/d38/class_g_u_i_window.html", [
      [ "GUICredits", "d8/df3/class_g_u_i_credits.html", null ],
      [ "GUIWindow_Book", "d6/d37/class_g_u_i_window___book.html", [
        [ "GUIWindow_AutonotesBook", "d6/dc4/struct_g_u_i_window___autonotes_book.html", null ],
        [ "GUIWindow_CalendarBook", "d8/d16/struct_g_u_i_window___calendar_book.html", null ],
        [ "GUIWindow_JournalBook", "dc/d98/struct_g_u_i_window___journal_book.html", null ],
        [ "GUIWindow_LloydsBook", "d6/d70/struct_g_u_i_window___lloyds_book.html", null ],
        [ "GUIWindow_MapBook", "d7/d06/struct_g_u_i_window___map_book.html", null ],
        [ "GUIWindow_QuestBook", "d3/d9c/struct_g_u_i_window___quest_book.html", null ],
        [ "GUIWindow_TownPortalBook", "d7/dee/struct_g_u_i_window___town_portal_book.html", null ]
      ] ],
      [ "GUIWindow_BooksButtonOverlay", "de/d1a/class_g_u_i_window___books_button_overlay.html", null ],
      [ "GUIWindow_CharacterRecord", "de/d17/class_g_u_i_window___character_record.html", null ],
      [ "GUIWindow_Chest", "d5/dcb/class_g_u_i_window___chest.html", null ],
      [ "GUIWindow_DebugMenu", "d4/d3d/class_g_u_i_window___debug_menu.html", null ],
      [ "GUIWindow_Dialogue", "db/d2b/class_g_u_i_window___dialogue.html", null ],
      [ "GUIWindow_GameKeyBindings", "d2/df0/class_g_u_i_window___game_key_bindings.html", null ],
      [ "GUIWindow_GameMenu", "d6/d7b/class_g_u_i_window___game_menu.html", null ],
      [ "GUIWindow_GameOptions", "dc/dc8/class_g_u_i_window___game_options.html", null ],
      [ "GUIWindow_GameVideoOptions", "d3/da6/class_g_u_i_window___game_video_options.html", null ],
      [ "GUIWindow_GenericDialogue", "d9/d04/class_g_u_i_window___generic_dialogue.html", null ],
      [ "GUIWindow_House", "d8/ddd/class_g_u_i_window___house.html", null ],
      [ "GUIWindow_Inventory", "d0/d4e/class_g_u_i_window___inventory.html", null ],
      [ "GUIWindow_Inventory_CastSpell", "d0/d91/class_g_u_i_window___inventory___cast_spell.html", null ],
      [ "GUIWindow_Load", "d0/dd2/class_g_u_i_window___load.html", null ],
      [ "GUIWindow_MainMenu", "d1/d86/class_g_u_i_window___main_menu.html", null ],
      [ "GUIWindow_Modal", "d8/d7e/class_g_u_i_window___modal.html", null ],
      [ "GUIWindow_PartyCreation", "d8/d1c/class_g_u_i_window___party_creation.html", null ],
      [ "GUIWindow_QuickReference", "d7/da1/class_g_u_i_window___quick_reference.html", null ],
      [ "GUIWindow_Rest", "d2/d13/class_g_u_i_window___rest.html", null ],
      [ "GUIWindow_RestWindow", "d9/dd7/class_g_u_i_window___rest_window.html", null ],
      [ "GUIWindow_Save", "db/ddc/class_g_u_i_window___save.html", null ],
      [ "GUIWindow_Scroll", "db/de8/class_g_u_i_window___scroll.html", null ],
      [ "GUIWindow_Spellbook", "d0/d1e/class_g_u_i_window___spellbook.html", null ],
      [ "GUIWindow_Transition", "d4/dc6/class_g_u_i_window___transition.html", null ],
      [ "GUIWindow_Travel", "de/d21/class_g_u_i_window___travel.html", null ],
      [ "OnButtonClick", "df/db2/class_on_button_click.html", null ],
      [ "OnButtonClick2", "d5/dea/class_on_button_click2.html", null ],
      [ "OnButtonClick3", "d1/d5e/class_on_button_click3.html", null ],
      [ "OnButtonClick4", "d2/d5e/class_on_button_click4.html", null ],
      [ "OnCancel", "d3/dd1/class_on_cancel.html", null ],
      [ "OnCancel2", "da/d9e/class_on_cancel2.html", null ],
      [ "OnCancel3", "d4/da9/class_on_cancel3.html", null ],
      [ "OnCastTargetedSpell", "d0/d30/class_on_cast_targeted_spell.html", null ],
      [ "OnSaveLoad", "d3/d83/class_on_save_load.html", null ]
    ] ],
    [ "gz_header_s", "d4/d86/structgz__header__s.html", null ],
    [ "gzFile_s", "df/db6/structgz_file__s.html", null ],
    [ "HWLContainer", "d6/d71/class_h_w_l_container.html", null ],
    [ "HWLHeader", "d6/da2/struct_h_w_l_header.html", null ],
    [ "HWLTexture", "d8/dc7/class_h_w_l_texture.html", null ],
    [ "HWLTextureHeader", "d3/d69/struct_h_w_l_texture_header.html", null ],
    [ "IAudioDataSource", "d0/df5/class_i_audio_data_source.html", [
      [ "AudioBaseDataSource", "da/dfd/class_audio_base_data_source.html", [
        [ "AudioBufferDataSource", "d0/de5/class_audio_buffer_data_source.html", null ],
        [ "AudioFileDataSource", "d6/dd4/class_audio_file_data_source.html", null ]
      ] ]
    ] ],
    [ "IAudioSample", "dc/d36/class_i_audio_sample.html", [
      [ "AudioSample16", "d5/d2b/class_audio_sample16.html", null ]
    ] ],
    [ "IAudioTrack", "dd/d42/class_i_audio_track.html", [
      [ "AudioTrackS16", "d3/dcc/class_audio_track_s16.html", null ]
    ] ],
    [ "Icon", "db/d60/class_icon.html", null ],
    [ "IconFrame_MM7", "d5/d1b/struct_icon_frame___m_m7.html", null ],
    [ "IconFrameTable", "d8/dc5/struct_icon_frame_table.html", null ],
    [ "Image", "de/d73/class_image.html", [
      [ "Texture", "d2/d7f/class_texture.html", [
        [ "TextureD3D", "d8/d6b/class_texture_d3_d.html", null ],
        [ "TextureOpenGL", "d9/d61/class_texture_open_g_l.html", null ]
      ] ]
    ] ],
    [ "ImageHelper", "d7/de4/class_image_helper.html", null ],
    [ "ImageLoader", "d7/d42/class_image_loader.html", [
      [ "Alpha_LOD_Loader", "d1/df5/class_alpha___l_o_d___loader.html", null ],
      [ "Bitmaps_LOD_Loader", "da/dc6/class_bitmaps___l_o_d___loader.html", null ],
      [ "ColorKey_LOD_Loader", "dd/db4/class_color_key___l_o_d___loader.html", null ],
      [ "Image16bit_LOD_Loader", "d6/d04/class_image16bit___l_o_d___loader.html", null ],
      [ "PCX_Loader", "d5/da3/class_p_c_x___loader.html", [
        [ "PCX_File_Loader", "d2/dad/class_p_c_x___file___loader.html", [
          [ "PCX_LOD_File_Loader", "d1/dd6/class_p_c_x___l_o_d___file___loader.html", null ]
        ] ],
        [ "PCX_LOD_Loader", "de/d07/class_p_c_x___l_o_d___loader.html", null ]
      ] ],
      [ "Sprites_LOD_Loader", "d2/d58/class_sprites___l_o_d___loader.html", null ]
    ] ],
    [ "IMemBuffer", "df/df1/class_i_mem_buffer.html", [
      [ "MemBuffer", "de/d32/class_mem_buffer.html", null ]
    ] ],
    [ "IMovie", "d9/d93/class_i_movie.html", [
      [ "Movie", "de/d14/class_movie.html", null ]
    ] ],
    [ "IndoorCameraD3D", "d9/de5/struct_indoor_camera_d3_d.html", null ],
    [ "IndoorCameraD3D_stru1", "d8/d94/struct_indoor_camera_d3_d__stru1.html", null ],
    [ "IndoorCameraD3D_stru2", "da/d37/struct_indoor_camera_d3_d__stru2.html", null ],
    [ "IndoorCameraD3D_stru3", "d6/d30/struct_indoor_camera_d3_d__stru3.html", null ],
    [ "IndoorCameraD3D_Vec3", "d8/deb/struct_indoor_camera_d3_d___vec3.html", [
      [ "IndoorCameraD3D_Vec4", "da/d76/struct_indoor_camera_d3_d___vec4.html", null ]
    ] ],
    [ "IndoorLocation", "d6/d9e/struct_indoor_location.html", null ],
    [ "Application::IocContainer", "d5/d77/class_application_1_1_ioc_container.html", null ],
    [ "Engine_::IocContainer", "d1/d12/class_engine___1_1_ioc_container.html", null ],
    [ "IRender", "d9/d20/class_i_render.html", [
      [ "RenderBase", "d9/d47/class_render_base.html", [
        [ "Render", "da/d7f/class_render.html", null ],
        [ "RenderOpenGL", "d1/d2c/class_render_open_g_l.html", null ]
      ] ]
    ] ],
    [ "Graphics::IRenderConfig", "d4/dae/class_graphics_1_1_i_render_config.html", null ],
    [ "Graphics::IRenderConfigFactory", "d2/db9/class_graphics_1_1_i_render_config_factory.html", null ],
    [ "Graphics::IRenderFactory", "d5/db2/class_graphics_1_1_i_render_factory.html", null ],
    [ "ITEM_VARIATION", "d4/dbb/struct_i_t_e_m___v_a_r_i_a_t_i_o_n.html", null ],
    [ "ItemDesc", "da/d8a/struct_item_desc.html", null ],
    [ "ItemEnchantment", "de/db8/struct_item_enchantment.html", null ],
    [ "ItemGen", "d7/d9c/struct_item_gen.html", null ],
    [ "ItemGen_Image_MM7", "d9/dc5/struct_item_gen___image___m_m7.html", null ],
    [ "ItemSpecialEnchantment", "d5/dfb/struct_item_special_enchantment.html", null ],
    [ "ItemsTable", "db/d39/struct_items_table.html", null ],
    [ "IVideoDataSource", "d8/d61/class_i_video_data_source.html", null ],
    [ "Keyboard", "d6/d7e/class_keyboard.html", null ],
    [ "KeyboardActionMapping", "d3/d10/struct_keyboard_action_mapping.html", null ],
    [ "LevelDecoration", "dd/d88/struct_level_decoration.html", null ],
    [ "Lightmap", "d2/da9/struct_lightmap.html", null ],
    [ "LightmapBuilder", "d8/d95/class_lightmap_builder.html", null ],
    [ "LightsData", "d7/d97/struct_lights_data.html", null ],
    [ "LightsStack_MobileLight_", "d1/d36/struct_lights_stack___mobile_light__.html", null ],
    [ "LightsStack_StationaryLight_", "d2/d9c/struct_lights_stack___stationary_light__.html", null ],
    [ "LloydBeacon", "df/d7d/struct_lloyd_beacon.html", null ],
    [ "LloydBeacon_Image_MM7", "df/d19/struct_lloyd_beacon___image___m_m7.html", null ],
    [ "SpellFX_Billboard::local_01", "dd/de0/struct_spell_f_x___billboard_1_1local__01.html", null ],
    [ "Localization", "dd/d88/class_localization.html", null ],
    [ "LocationTime_stru1", "d5/da2/struct_location_time__stru1.html", null ],
    [ "LODSpriteHeader", "d3/ddd/struct_l_o_d_sprite_header.html", [
      [ "LODSprite", "d5/d3a/struct_l_o_d_sprite.html", null ]
    ] ],
    [ "LODSpriteLine", "df/ddf/struct_l_o_d_sprite_line.html", null ],
    [ "Log", "d6/d70/class_log.html", null ],
    [ "MapInfo", "db/ddb/struct_map_info.html", null ],
    [ "MapsLongTimer", "da/d77/struct_maps_long_timer.html", null ],
    [ "MapStats", "d0/d23/struct_map_stats.html", null ],
    [ "Matrix3x3_float_", "dd/d5a/struct_matrix3x3__float__.html", null ],
    [ "Application::Menu", "df/dac/class_application_1_1_menu.html", null ],
    [ "MobileLight", "d2/d53/struct_mobile_light.html", null ],
    [ "MonsterDesc", "d3/db3/struct_monster_desc.html", null ],
    [ "MonsterDesc_mm6", "d8/d7a/struct_monster_desc__mm6.html", null ],
    [ "MonsterInfo", "d4/dff/struct_monster_info.html", null ],
    [ "MonsterList", "d5/da3/struct_monster_list.html", null ],
    [ "MonsterStats", "d3/df5/struct_monster_stats.html", null ],
    [ "Mouse", "d7/dc5/class_mouse.html", null ],
    [ "VideoList::MovieHeader", "d1/dd8/struct_video_list_1_1_movie_header.html", null ],
    [ "MPlayer", "d0/db7/class_m_player.html", null ],
    [ "VideoList::Node", "d0/db8/struct_video_list_1_1_node.html", null ],
    [ "NPCData", "d8/dc1/struct_n_p_c_data.html", null ],
    [ "NPCData_Image_MM7", "da/d9d/struct_n_p_c_data___image___m_m7.html", null ],
    [ "NPCGreeting", "d3/dce/struct_n_p_c_greeting.html", null ],
    [ "NPCProfession", "da/d2a/struct_n_p_c_profession.html", null ],
    [ "NPCProfessionChance", "de/de6/struct_n_p_c_profession_chance.html", null ],
    [ "NPCStats", "d5/d11/struct_n_p_c_stats.html", null ],
    [ "NPCTopic", "d6/d73/struct_n_p_c_topic.html", null ],
    [ "ObjectDesc", "d9/d88/struct_object_desc.html", null ],
    [ "ObjectDesc_mm6", "d8/d76/struct_object_desc__mm6.html", null ],
    [ "ObjectList", "dc/d41/class_object_list.html", null ],
    [ "ODMFace", "d3/df8/struct_o_d_m_face.html", null ],
    [ "ODMFace_MM7", "dd/dcf/struct_o_d_m_face___m_m7.html", null ],
    [ "ODMHeader", "d9/d1c/struct_o_d_m_header.html", null ],
    [ "ODMRenderParams", "d5/df7/struct_o_d_m_render_params.html", null ],
    [ "OpenALSoundProvider", "d9/d98/class_open_a_l_sound_provider.html", null ],
    [ "OptionsMenuSkin", "d4/de3/struct_options_menu_skin.html", null ],
    [ "OSWindow", "db/da4/class_o_s_window.html", [
      [ "Sdl2Window", "d4/d57/class_sdl2_window.html", null ],
      [ "WinApiWindow", "d3/da4/class_win_api_window.html", null ]
    ] ],
    [ "OSWindowFactory", "d2/d4c/class_o_s_window_factory.html", null ],
    [ "OtherOverlay", "db/dca/struct_other_overlay.html", null ],
    [ "OtherOverlay_Image_MM7", "dc/dfd/struct_other_overlay___image___m_m7.html", null ],
    [ "OtherOverlayList", "d8/df0/struct_other_overlay_list.html", null ],
    [ "OtherOverlayList_Image_MM7", "d2/d11/struct_other_overlay_list___image___m_m7.html", null ],
    [ "OutdoorLocation", "d1/d55/struct_outdoor_location.html", null ],
    [ "OutdoorLocationTerrain", "d7/dbf/struct_outdoor_location_terrain.html", null ],
    [ "OutdoorLocationTileType", "d2/d94/struct_outdoor_location_tile_type.html", null ],
    [ "OverlayDesc", "d1/d39/struct_overlay_desc.html", null ],
    [ "OverlayList", "d8/d68/struct_overlay_list.html", null ],
    [ "PaletteManager", "d3/db3/struct_palette_manager.html", null ],
    [ "Particle", "dd/d47/struct_particle.html", null ],
    [ "Particle_sw", "d8/d4e/struct_particle__sw.html", null ],
    [ "ParticleEngine", "dd/d2d/class_particle_engine.html", null ],
    [ "Party", "d0/d14/struct_party.html", null ],
    [ "Party_Image_MM7", "d6/dee/struct_party___image___m_m7.html", null ],
    [ "PartyTimeStruct", "d5/dfa/struct_party_time_struct.html", null ],
    [ "PartyTimeStruct_Image_MM7", "df/da1/struct_party_time_struct___image___m_m7.html", null ],
    [ "PCXHeader", "dc/d7e/struct_p_c_x_header.html", null ],
    [ "Plane_float_", "dd/d96/struct_plane__float__.html", null ],
    [ "Plane_int_", "d0/d75/struct_plane__int__.html", null ],
    [ "Player", "d3/db1/struct_player.html", null ],
    [ "Player_Image_MM7", "d9/d65/struct_player___image___m_m7.html", null ],
    [ "PlayerBuffAnim", "d1/d66/struct_player_buff_anim.html", null ],
    [ "PlayerCreation_AttributeProps", "d0/d9d/struct_player_creation___attribute_props.html", null ],
    [ "PlayerEquipment", "d4/dab/union_player_equipment.html", null ],
    [ "PlayerEquipment_Image_MM7", "de/d2c/union_player_equipment___image___m_m7.html", null ],
    [ "PlayerFrame", "d2/d3b/struct_player_frame.html", null ],
    [ "PlayerFrameTable", "db/d2f/struct_player_frame_table.html", null ],
    [ "PlayerSpellbookChapter", "de/d26/struct_player_spellbook_chapter.html", null ],
    [ "PlayerSpellbookChapter_Image_MM7", "dd/d62/struct_player_spellbook_chapter___image___m_m7.html", null ],
    [ "PlayerSpells", "d2/dbe/struct_player_spells.html", null ],
    [ "PlayerSpells_Image_MM7", "d9/db3/struct_player_spells___image___m_m7.html", null ],
    [ "Point", "d8/dc8/struct_point.html", null ],
    [ "Polygon", "d4/dd7/struct_polygon.html", null ],
    [ "ProjectileAnim", "df/d28/struct_projectile_anim.html", null ],
    [ "Random", "da/d64/struct_random.html", null ],
    [ "RcOverride", "d7/de1/struct_rc_override.html", null ],
    [ "Rect", "d8/d1e/struct_rect.html", null ],
    [ "RenderBillboard", "dd/d3e/struct_render_billboard.html", null ],
    [ "RenderBillboardD3D", "da/db4/struct_render_billboard_d3_d.html", null ],
    [ "RenderD3D", "de/db5/class_render_d3_d.html", null ],
    [ "RenderD3D__DevInfo", "d4/df2/struct_render_d3_d_____dev_info.html", null ],
    [ "RenderD3D_aux", "da/dfe/struct_render_d3_d__aux.html", null ],
    [ "RenderD3D_D3DDevDesc", "d1/dd7/struct_render_d3_d___d3_d_dev_desc.html", null ],
    [ "RenderVertexD3D3", "d0/df7/struct_render_vertex_d3_d3.html", null ],
    [ "RenderVertexSoft", "db/d1a/struct_render_vertex_soft.html", null ],
    [ "SavegameHeader", "d1/d2a/struct_savegame_header.html", null ],
    [ "SavegameList", "dd/df4/struct_savegame_list.html", null ],
    [ "SDL_AssertData", "d7/d08/struct_s_d_l___assert_data.html", null ],
    [ "SDL_atomic_t", "de/d13/struct_s_d_l__atomic__t.html", null ],
    [ "SDL_AudioCVT", "d1/d4b/struct_s_d_l___audio_c_v_t.html", null ],
    [ "SDL_AudioDeviceEvent", "d4/d9b/struct_s_d_l___audio_device_event.html", null ],
    [ "SDL_AudioSpec", "d1/d75/struct_s_d_l___audio_spec.html", null ],
    [ "SDL_Color", "d5/dcc/struct_s_d_l___color.html", null ],
    [ "SDL_CommonEvent", "dd/d06/struct_s_d_l___common_event.html", null ],
    [ "SDL_ControllerAxisEvent", "da/d9e/struct_s_d_l___controller_axis_event.html", null ],
    [ "SDL_ControllerButtonEvent", "d9/d15/struct_s_d_l___controller_button_event.html", null ],
    [ "SDL_ControllerDeviceEvent", "da/d81/struct_s_d_l___controller_device_event.html", null ],
    [ "SDL_DisplayEvent", "de/d93/struct_s_d_l___display_event.html", null ],
    [ "SDL_DisplayMode", "d1/d16/struct_s_d_l___display_mode.html", null ],
    [ "SDL_DollarGestureEvent", "d7/dec/struct_s_d_l___dollar_gesture_event.html", null ],
    [ "SDL_DropEvent", "df/d97/struct_s_d_l___drop_event.html", null ],
    [ "SDL_Event", "df/d1f/union_s_d_l___event.html", null ],
    [ "SDL_Finger", "da/db6/struct_s_d_l___finger.html", null ],
    [ "SDL_FPoint", "d8/d8f/struct_s_d_l___f_point.html", null ],
    [ "SDL_FRect", "da/dd7/struct_s_d_l___f_rect.html", null ],
    [ "SDL_GameControllerButtonBind", "dd/dc4/struct_s_d_l___game_controller_button_bind.html", null ],
    [ "SDL_HapticCondition", "d1/d00/struct_s_d_l___haptic_condition.html", null ],
    [ "SDL_HapticConstant", "d7/d4d/struct_s_d_l___haptic_constant.html", null ],
    [ "SDL_HapticCustom", "de/d46/struct_s_d_l___haptic_custom.html", null ],
    [ "SDL_HapticDirection", "dc/dc3/struct_s_d_l___haptic_direction.html", null ],
    [ "SDL_HapticEffect", "d4/d80/union_s_d_l___haptic_effect.html", null ],
    [ "SDL_HapticLeftRight", "d3/d93/struct_s_d_l___haptic_left_right.html", null ],
    [ "SDL_HapticPeriodic", "d1/d6b/struct_s_d_l___haptic_periodic.html", null ],
    [ "SDL_HapticRamp", "d2/df5/struct_s_d_l___haptic_ramp.html", null ],
    [ "SDL_JoyAxisEvent", "d3/d15/struct_s_d_l___joy_axis_event.html", null ],
    [ "SDL_JoyBallEvent", "df/d8b/struct_s_d_l___joy_ball_event.html", null ],
    [ "SDL_JoyButtonEvent", "d7/de3/struct_s_d_l___joy_button_event.html", null ],
    [ "SDL_JoyDeviceEvent", "d7/d5b/struct_s_d_l___joy_device_event.html", null ],
    [ "SDL_JoyHatEvent", "d8/d59/struct_s_d_l___joy_hat_event.html", null ],
    [ "SDL_JoystickGUID", "d5/d5c/struct_s_d_l___joystick_g_u_i_d.html", null ],
    [ "SDL_KeyboardEvent", "d8/db8/struct_s_d_l___keyboard_event.html", null ],
    [ "SDL_Keysym", "d4/de7/struct_s_d_l___keysym.html", null ],
    [ "SDL_MessageBoxButtonData", "d5/d6d/struct_s_d_l___message_box_button_data.html", null ],
    [ "SDL_MessageBoxColor", "d0/d93/struct_s_d_l___message_box_color.html", null ],
    [ "SDL_MessageBoxColorScheme", "db/d58/struct_s_d_l___message_box_color_scheme.html", null ],
    [ "SDL_MessageBoxData", "d0/d2c/struct_s_d_l___message_box_data.html", null ],
    [ "SDL_MouseButtonEvent", "d9/d8f/struct_s_d_l___mouse_button_event.html", null ],
    [ "SDL_MouseMotionEvent", "d2/d18/struct_s_d_l___mouse_motion_event.html", null ],
    [ "SDL_MouseWheelEvent", "d8/d9b/struct_s_d_l___mouse_wheel_event.html", null ],
    [ "SDL_MultiGestureEvent", "d7/d64/struct_s_d_l___multi_gesture_event.html", null ],
    [ "SDL_OSEvent", "d6/d78/struct_s_d_l___o_s_event.html", null ],
    [ "SDL_Palette", "de/d4f/struct_s_d_l___palette.html", null ],
    [ "SDL_PixelFormat", "de/d29/struct_s_d_l___pixel_format.html", null ],
    [ "SDL_Point", "dd/d4e/struct_s_d_l___point.html", null ],
    [ "SDL_QuitEvent", "d6/d71/struct_s_d_l___quit_event.html", null ],
    [ "SDL_Rect", "d4/dda/struct_s_d_l___rect.html", null ],
    [ "SDL_RendererInfo", "d8/d04/struct_s_d_l___renderer_info.html", null ],
    [ "SDL_RWops", "d2/d3b/struct_s_d_l___r_wops.html", null ],
    [ "SDL_SensorEvent", "dc/dd1/struct_s_d_l___sensor_event.html", null ],
    [ "SDL_Surface", "d6/d0f/struct_s_d_l___surface.html", null ],
    [ "SDL_SysWMEvent", "d8/d14/struct_s_d_l___sys_w_m_event.html", null ],
    [ "SDL_SysWMinfo", "d1/d59/struct_s_d_l___sys_w_minfo.html", null ],
    [ "SDL_SysWMmsg", "de/deb/struct_s_d_l___sys_w_mmsg.html", null ],
    [ "SDL_TextEditingEvent", "d9/d58/struct_s_d_l___text_editing_event.html", null ],
    [ "SDL_TextInputEvent", "d8/d47/struct_s_d_l___text_input_event.html", null ],
    [ "SDL_TouchFingerEvent", "d8/d17/struct_s_d_l___touch_finger_event.html", null ],
    [ "SDL_UserEvent", "d7/d78/struct_s_d_l___user_event.html", null ],
    [ "SDL_version", "d9/d84/struct_s_d_l__version.html", null ],
    [ "SDL_WindowEvent", "d1/d00/struct_s_d_l___window_event.html", null ],
    [ "SDL_WindowShapeMode", "dd/da3/struct_s_d_l___window_shape_mode.html", null ],
    [ "SDL_WindowShapeParams", "d3/d93/union_s_d_l___window_shape_params.html", null ],
    [ "SDLTest_CommonState", "d8/d8d/struct_s_d_l_test___common_state.html", null ],
    [ "SDLTest_Crc32Context", "d2/d0b/struct_s_d_l_test___crc32_context.html", null ],
    [ "SDLTest_Md5Context", "d4/d44/struct_s_d_l_test___md5_context.html", null ],
    [ "SDLTest_RandomContext", "d8/d07/struct_s_d_l_test___random_context.html", null ],
    [ "SDLTest_SurfaceImage_s", "d9/d47/struct_s_d_l_test___surface_image__s.html", null ],
    [ "SDLTest_TestCaseReference", "d2/dd7/struct_s_d_l_test___test_case_reference.html", null ],
    [ "SDLTest_TestSuiteReference", "d2/d34/struct_s_d_l_test___test_suite_reference.html", null ],
    [ "SkyBillboardStruct", "da/d8e/struct_sky_billboard_struct.html", null ],
    [ "SoftwareBillboard", "d2/d7a/struct_software_billboard.html", null ],
    [ "SoundDesc_mm6", "d0/d6f/struct_sound_desc__mm6.html", [
      [ "SoundDesc", "d4/d4d/struct_sound_desc.html", null ]
    ] ],
    [ "AudioPlayer::SoundHeader", "d7/d01/struct_audio_player_1_1_sound_header.html", null ],
    [ "SoundHeader_mm7", "d5/d3c/struct_sound_header__mm7.html", null ],
    [ "SoundInfo", "d2/d14/class_sound_info.html", null ],
    [ "SoundList", "db/d39/class_sound_list.html", null ],
    [ "spark_point_struct", "d1/dc9/structspark__point__struct.html", null ],
    [ "SpawnPointMM6", "d2/d8f/struct_spawn_point_m_m6.html", null ],
    [ "SpawnPointMM7", "d5/d3b/struct_spawn_point_m_m7.html", null ],
    [ "SpellBookIconPos", "d1/d1f/struct_spell_book_icon_pos.html", null ],
    [ "SpellBuff", "db/d1e/struct_spell_buff.html", null ],
    [ "SpellBuff_Image_MM7", "de/d35/struct_spell_buff___image___m_m7.html", null ],
    [ "SpellData", "d0/d82/class_spell_data.html", null ],
    [ "SpellFX_Billboard", "d2/d83/struct_spell_f_x___billboard.html", null ],
    [ "SpellFxRenderer", "db/d64/struct_spell_fx_renderer.html", null ],
    [ "SpellInfo", "df/daf/struct_spell_info.html", null ],
    [ "SpellStats", "d1/d36/struct_spell_stats.html", null ],
    [ "sPoint", "dc/d34/structs_point.html", null ],
    [ "Sprite", "d7/dbf/class_sprite.html", null ],
    [ "SpriteFrame", "dc/df9/class_sprite_frame.html", null ],
    [ "SpriteFrame_MM6", "df/d14/struct_sprite_frame___m_m6.html", [
      [ "SpriteFrame_MM7", "dc/d95/struct_sprite_frame___m_m7.html", null ]
    ] ],
    [ "SpriteFrameTable", "de/da7/struct_sprite_frame_table.html", null ],
    [ "SpriteObject", "d0/d5a/struct_sprite_object.html", null ],
    [ "stat_coord", "d9/df0/structstat__coord.html", null ],
    [ "StationaryLight", "d5/ddc/struct_stationary_light.html", null ],
    [ "StorylineRecord", "d2/d28/struct_storyline_record.html", null ],
    [ "StorylineText", "d8/db2/struct_storyline_text.html", null ],
    [ "OpenALSoundProvider::StreamingTrackBuffer", "d6/d42/struct_open_a_l_sound_provider_1_1_streaming_track_buffer.html", null ],
    [ "stru10", "d0/da9/structstru10.html", null ],
    [ "stru123", "d1/dd8/structstru123.html", null ],
    [ "stru141_actor_collision_object", "df/d2b/structstru141__actor__collision__object.html", null ],
    [ "stru154", "db/deb/structstru154.html", null ],
    [ "stru159", "d9/d5a/structstru159.html", null ],
    [ "stru160", "d5/dc1/structstru160.html", [
      [ "stru16x", "dd/dd4/structstru16x.html", null ]
    ] ],
    [ "stru193_math", "d6/d38/structstru193__math.html", null ],
    [ "stru262_TurnBased", "d1/d28/structstru262___turn_based.html", null ],
    [ "stru298", "d3/dc7/structstru298.html", null ],
    [ "stru2_LineList", "d2/dbb/structstru2___line_list.html", null ],
    [ "stru312", "d3/de3/structstru312.html", null ],
    [ "stru314", "d4/d02/structstru314.html", null ],
    [ "stru315", "d9/dbd/structstru315.html", null ],
    [ "stru316", "df/d45/structstru316.html", null ],
    [ "stru319", "db/d28/structstru319.html", null ],
    [ "stru324_spell_id_to_sprite_mapping", "d1/d92/structstru324__spell__id__to__sprite__mapping.html", null ],
    [ "stru336", "de/d2a/structstru336.html", null ],
    [ "stru337", "d3/d6a/structstru337.html", null ],
    [ "stru337_stru0", "dd/d58/structstru337__stru0.html", null ],
    [ "stru352", "d4/d8a/structstru352.html", null ],
    [ "stru355", "d0/def/structstru355.html", null ],
    [ "stru365_travel_info", "d0/d8f/structstru365__travel__info.html", null ],
    [ "stru367", "d9/dbc/structstru367.html", null ],
    [ "stru6_stru2", "d7/ddc/structstru6__stru2.html", null ],
    [ "stru9", "da/d1a/structstru9.html", null ],
    [ "SummonedItem", "df/de0/struct_summoned_item.html", null ],
    [ "SwsFilter", "dd/ddf/struct_sws_filter.html", null ],
    [ "SwsVector", "d9/dd3/struct_sws_vector.html", null ],
    [ "Texture_MM7", "d0/ded/struct_texture___m_m7.html", null ],
    [ "TextureFrame", "d1/df3/class_texture_frame.html", null ],
    [ "TextureFrame_MM7", "de/d87/struct_texture_frame___m_m7.html", null ],
    [ "TextureFrameTable", "dd/d55/struct_texture_frame_table.html", null ],
    [ "TextureHeader", "d6/de3/struct_texture_header.html", null ],
    [ "TileDesc", "de/d61/class_tile_desc.html", null ],
    [ "TileDesc_MM7", "d8/d5d/struct_tile_desc___m_m7.html", null ],
    [ "TileTable", "d2/d6c/struct_tile_table.html", null ],
    [ "Timer", "d8/da1/struct_timer.html", null ],
    [ "Timer_Image_MM7", "d4/dfe/struct_timer___image___m_m7.html", null ],
    [ "TownPortalData", "da/dff/struct_town_portal_data.html", null ],
    [ "OpenALSoundProvider::TrackBuffer", "d3/d12/struct_open_a_l_sound_provider_1_1_track_buffer.html", null ],
    [ "TrailParticle", "d9/dad/struct_trail_particle.html", null ],
    [ "TrailParticleGenerator", "d6/d55/struct_trail_particle_generator.html", null ],
    [ "TravelInfo", "db/d9e/struct_travel_info.html", null ],
    [ "TurnBased_QueueElem", "d8/de8/struct_turn_based___queue_elem.html", null ],
    [ "UIAnimation", "d0/d6f/class_u_i_animation.html", null ],
    [ "UIAnimation_MM7", "d4/dba/struct_u_i_animation___m_m7.html", null ],
    [ "unaligned_16", "d3/d1d/unionunaligned__16.html", null ],
    [ "unaligned_32", "d3/dd5/unionunaligned__32.html", null ],
    [ "unaligned_64", "d2/d01/unionunaligned__64.html", null ],
    [ "vaapi_context", "d7/d30/structvaapi__context.html", null ],
    [ "Vec2< T >", "db/db1/struct_vec2.html", [
      [ "Vec3< T >", "df/d8a/struct_vec3.html", null ]
    ] ],
    [ "Vec2< int >", "db/db1/struct_vec2.html", [
      [ "Vec3< int >", "df/d8a/struct_vec3.html", null ]
    ] ],
    [ "Vec3_float_", "d5/d06/struct_vec3__float__.html", null ],
    [ "Vec4_int_", "d5/d07/struct_vec4__int__.html", null ],
    [ "vector", null, [
      [ "BSPModelList", "d1/d16/class_b_s_p_model_list.html", null ]
    ] ],
    [ "VertexBuffer", "d0/dc4/struct_vertex_buffer.html", null ],
    [ "VideoList", "d3/dfa/class_video_list.html", null ],
    [ "ViewingParams", "d4/d10/struct_viewing_params.html", null ],
    [ "Viewport", "de/d02/struct_viewport.html", null ],
    [ "Vis", "d0/def/class_vis.html", null ],
    [ "Vis_ObjectInfo", "d1/d04/struct_vis___object_info.html", null ],
    [ "Vis_SelectionFilter", "db/dc6/struct_vis___selection_filter.html", null ],
    [ "Vis_SelectionList", "de/d0c/struct_vis___selection_list.html", null ],
    [ "Weather", "d2/d72/class_weather.html", null ],
    [ "WindowManager", "d2/d3b/class_window_manager.html", null ],
    [ "xvmc_pix_fmt", "df/d3e/structxvmc__pix__fmt.html", null ],
    [ "z_stream_s", "d7/d8a/structz__stream__s.html", null ]
];